const express = require("express");
const router = express.Router();
const {createProduct, getAllProducts, updateProduct, deleteProduct, addImagesToProduct} = require("../controllers/productController");
const authMiddleware = require("../Middleware/authMiddleware");
const uploadImage = require("../Middleware/uploadimages");
router.post("/products", authMiddleware, uploadImage, createProduct);
router.get("/products", getAllProducts);
router.put("/products/:productId", authMiddleware, updateProduct);
router.delete("/products/:id", authMiddleware, deleteProduct);
router.put("/products/:id/images", uploadImage, addImagesToProduct);
module.exports = router;