const express = require("express");
const router = express.Router();
const {createProduct, getAllProducts, updateProduct, deleteProduct} = require("../controllers/productController");
const authMiddleware = require("../Middleware/authMiddleware");
const uploadImageProvider = require("../Middleware/uploadimages");
router.post("/products", authMiddleware, uploadImageProvider, createProduct);
router.get("/products",  getAllProducts);
router.put("/:productId", updateProduct);
router.delete("/:id", authMiddleware, deleteProduct);
module.exports =router;